#ifndef _ENUMS_H
#define _ENUMS_H




enum CV_TYPE {  // 类型
	FRIENDLY,   // 友善
	NEUTRAL,    // 中立
	AGGRESIVE   // 好斗
};

enum IRESULT {
	IR_NOTHING,
	IR_COOPERATION,
	
	IR_FVICTORY,  IR_FVICTORYKILL,
	IR_FDEFEAT,   IR_FDEFEATDIED,
	IR_AVICTORY,  IR_AFVICTORYKILL,
	IR_ADEFEAT,   IR_ADEFEATDIED,
};

//enum ITYPE {IT_NOINTERACT,IT_COOPERATION,IT_FIGHT};

//inline ITYPE IR2IT(const IRESULT IR) { return ((IR > 2) ? IT_FIGHT:(IR?IT_COOPERATION:IT_NOINTERACT)); };



#endif /*_ENUMS_H*/